In [3]:
import numpy as np
a1 = np.array([1,2,3])
print(a1)


[1 2 3]


In [3]:
a1[0] = 8
print(a1)

[8 2 3]


In [4]:
a2 = np.array([1.2525,2,"abc", 3.1415])
print(a2)
print(a2[[1,2]])
a2[2] = 100
print(a2)
a2[0] = "xd"
print(a2)

['1.2525' '2' 'abc' '3.1415']
['2' 'abc']
['1.2525' '2' '100' '3.1415']
['xd' '2' '100' '3.1415']


In [17]:
a3 = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
print(a3)
print(a3[0,0])
print(a3[2])
print(a3[:][1])
print(a3[:, 1])

# lista=[[1,2,3], [4,5,6], [7, 8, 9]]
# print(lista[:, 1])                       <----- nie działa

print(a3[1:, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[7 8 9]
[4 5 6]
[2 5 8]
[6 9]


In [52]:
one = np.ones((4,2,2,2), dtype='int32')
print(one)

[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]


In [22]:
pusty = np.empty((10,10))
print(pusty)
print(pusty.itemsize)
print(pusty.size)
print(pusty.nbytes)

pusty[0][0] = "abcd"


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
8
100
800


ValueError: could not convert string to float: 'abcd'