In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3])
print(a1)


In [ ]:
a1[0] = 8
print(a1)

In [ ]:
a2 = np.array([1.2525,2,"abc", 3.1415])
print(a2)
print(a2[[1,2]])
a2[2] = 100
print(a2)
a2[0] = "xd"
print(a2)

In [ ]:
a3 = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
print(a3)
print(a3[0,0])
print(a3[2])
print(a3[:][1])
print(a3[:, 1])

# lista=[[1,2,3], [4,5,6], [7, 8, 9]]
# print(lista[:, 1])                       <----- nie działa

print(a3[1:, 2])

In [ ]:
one = np.ones((4,2,2,2), dtype='int32')
print(one)

In [67]:
pusty = np.empty((10,10))
# print(pusty)
print(pusty.itemsize)
print(pusty.size)
print(pusty.nbytes)

pusty[0][0] = 5


8
100
800



# ________________________________________________________________________________________________________________


In [38]:
lista = [[1,2,3], [4,5,6], [7,8,9]]
print(lista[:][0])
# Zwykłe listy pythonowe nie mają indeksowania wielowymiarowego, ale numpy ma

lista = np.array(lista)
print(lista[:, 0])

[1, 2, 3]
[1 4 7]


In [32]:
lista.sum()

np.int64(45)

In [34]:
lista.mean()

np.float64(5.0)

In [36]:
lista.std()

np.float64(2.581988897471611)

In [51]:
lista[:, 0].sum()

np.int64(12)

In [54]:
# 0 - pionowo, 1 - poziomo
print(lista.sum(axis=0))
print(lista.sum(axis=1))

[12 15 18]
[ 6 15 24]


In [56]:
lista.sum(axis=0)[0]

np.int64(12)

In [59]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [63]:
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
a[[True, False, False, True]]

array([0, 3])

In [64]:
a >= 2

array([False, False,  True,  True])

In [65]:
a[a >= 2]
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

array([2, 3])