In [2]:
import numpy as np
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [3]:
a1[0] = 8
print(a1)

[8 2 3]


In [5]:
a2 = np.array([1,2,"abc", 3.1415])
print(a2)
print(a2[[1,2]])

['1' '2' 'abc' '3.1415']
['2' 'abc']


In [ ]:
a3 = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
print(a3)
print(a3[0,0])
print(a3[2])
print(a3[:][1])
print(a3[:, 1])

# lista=[[1,2,3], [4,5,6], [7, 8, 9]]
# print(lista[:, 1])                       <----- nie działa

print(a3[1:, 2])

In [52]:
one = np.ones((4,2,2,2), dtype='int32')
print(one)

[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]
